// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0zeJL9OC91Z02X6a72DbOCFm4sO93bFg',
    appId: '1:444866212667:web:236db8e31554376842bd1e',
    messagingSenderId: '444866212667',
    projectId: 'test-4cbff',
    authDomain: 'test-4cbff.firebaseapp.com',
    storageBucket: 'test-4cbff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfyhdEa2X-WFX1tGf-IdEasEcoB7ZVQ0',
    appId: '1:459092079155:android:bb8c2ef3b78fd35a42e946',
    messagingSenderId: '459092079155',
    projectId: 'spotify-8aec7',
    storageBucket: 'spotify-8aec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAoxrVbEWZKJO32nxBqi-ermHJAQKbq_U',
    appId: '1:444866212667:ios:63944111cba3c83042bd1e',
    messagingSenderId: '444866212667',
    projectId: 'test-4cbff',
    storageBucket: 'test-4cbff.appspot.com',
    iosBundleId: 'com.example.spotifyCloneFr.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAoxrVbEWZKJO32nxBqi-ermHJAQKbq_U',
    appId: '1:444866212667:ios:63944111cba3c83042bd1e',
    messagingSenderId: '444866212667',
    projectId: 'test-4cbff',
    storageBucket: 'test-4cbff.appspot.com',
    iosBundleId: 'com.example.spotifyCloneFr.RunnerTests',
  );
}
